# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  input:          GFM

# Permalinks
permalink:        pretty

# Setup
title:            Data Carpentry -for- Ecologists
description:      'Teaching the tools to get computers to do cool science'
url:              http://mvevans89.github.io/ECOL-8030
baseurl:          /ECOL-8030
email:            mvevans@uga.edu
feedbackurl:      mailto:mvevans@uga.edu
author:
  name:           'Michelle Evans'
  url:            http://gsa.ecology.uga.edu/

github:
  repo:           https://github.com/mvevans89/ECOL-8030
  #               Be sure the 'Issues' feature is activated in 'Settings'
